version: '3.5'

# You may use the following (Linux) command to start Gigwa by dynamically setting the docker0 IP address:
# export docker0=$(ip a list docker0 | grep "inet " | sed 's/^ *//g' | awk -F'[ |/]' '{print $2}') && docker-compose up -d && sleep 2 && xdg-open http://$docker0:80/gigwa &> /dev/null

services:
  tomcat:
    depends_on:
      - mongo
    image: guilhemsempere/gigwa:2.5-RELEASE
    ports:
      - 80:8080 # You may amend the external port only (left hand side). By default, webapp URL will be http://host.ip:8080/gigwa
    restart: always
    hostname: gigwamaster
    links:
      - "mongo:gigwastorage"
    environment:
      MONGO_IP: gigwastorage 
      MONGO_PORT: 27017 # Must match mongo container external port
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:?err} 
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:?err} 
      HOST_LOCALE: "${LANG}"
#     casServerURL: https://sso.cirad.fr:443                # URL of the CAS server to use for Single-Sign-On
#     enforcedWebapRootUrl: http://${docker0}:8080/gigwa    # Gigwa base-URL for CAS to direct to after login. System will attempt guessing it if not provided, but it's always better to specify it
#     casOrganization: MyOrganization                       # Not required, will only be displayed on login page if provided
      
    volumes:
      - type: bind
        source: ./config/index.jsp
        target: /usr/local/tomcat/webapps/gigwa/index.jsp
      - type: bind
        source: ./config/images
        target: /usr/local/tomcat/webapps/gigwa/images
      - type: volume
        source: gigwa
        target: /usr/local/tomcat/config
#      - type: bind                      # Uncomment this line to make dumps accessible from the host machine         
#        source: /tmp/gigwaDockerDumps   # Uncomment this line to make dumps accessible from the host machine (you may also want to set the path you wish to use as source)
#        target: /root/gigwaDumps        # Uncomment this line to make dumps accessible from the host machine (must match the dumpFolder attribute's value in config.properties)
  mongo:
    image: mongo:4.2.18
    hostname: gigwastorage
    restart: always
    command: --profile 0 --slowms 60000 --storageEngine wiredTiger --wiredTigerCollectionBlockCompressor=zstd --directoryperdb --quiet
    ports:
      - 27017 # You may amend the external port only (left hand side), which must match the above MONGO_PORT
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:?err} 
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:?err} 
    volumes:
      - type: volume
        source: mongo
        target: /data/db

volumes:
  gigwa:
  mongo:
